#!/usr/bin/env bash
# Configure your Nginx server to have a 

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
sudo echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
newsite="\\\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}"
sudo sed -i "27i $newsite" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
