#!/usr/bin/env bash
# Double the number of webservers
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx

# config
sudo ufw allow 'Nginx HTTP'

# default page
echo "Holberton School" > /var/www/index.html
sed -i '/server_name _;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# page 404
echo "Ceci n'est pas une page" > /var/www/html/404_error.html
sudo sed -i "/server_name _;/a error_page 404 /404_error.html;" /etc/nginx/sites-available/default

# custom Nginx response header.
sudo sed -i "/server_name _;/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
sudo service nginx start
