#!/usr/bin/env bash
# Double the number of webservers
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
sudo touch /var/www/html/index.html
echo "Holberton School" > /var/www/html/index.html
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo touch /var/www/html/404.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html
sudo sed -i "/server_name _;/a error_page 404 /404.html;" /etc/nginx/sites-available/default
sudo sed -i "/server_name _;/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
sudo service nginx start
