#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
sudo apt-get -y update
sudo apt-get -y install software-properties-common
sudo apt-get -y install haproxy=1.6.\*

printf %s "
frontend http
    bind *:80
    default_backend web-backend
backend web-backend
    balance roundrobin
    server 2236-web-01 34.74.83.73
    server 2236-web-02 54.172.228.152" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
