#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times

COUNT=1
while [ "$COUNT" -le 10 ]; do
        if [ "$COUNT" -eq 4 ]; then
                echo "bad luck"
        elif [ "$COUNT" -eq 8 ]; then
                echo "good luck"
        else
                echo "Holberton School"
        fi
        COUNT=$((COUNT + 1))
done
