#!/usr/bin/env bash
# script that displays the time for 12 hours and 59 minutes

HOUR=0
while [ "$HOUR" -lt 13 ]; do
        echo "Hour: $HOUR"
        MINUTE=1
        while [ "$MINUTE" -lt 60 ]; do
                echo "$MINUTE"
                MINUTE=$((MINUTE + 1))
        done
        HOUR=$((HOUR + 1))
done
